[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
indexmap = "2.7.0"
itertools = "0.13.0"
nalgebra = "0.33.2"
nom = "7.1.3"
ordered-float = "4.5.0"
regex = "1.11.1"
